import { Media, Book, Movie, CD } from "./resources.js";
const godfather = new Book('Mario Puzo', 'The Godfather', 532);
godfather.addRating(8);
godfather.addRating(7);
godfather.addRating(10);
godfather.addRating(10);
godfather.addRating(9);
godfather.getAverageRating();
godfather.toggleCheckOutStatus();
console.log(godfather);

const interstellar = new Movie('Christopher Nolan', 'Interstellar', 160);
interstellar.addRating(10);
interstellar.addRating(8);
interstellar.addRating(7);
interstellar.addRating(10);
interstellar.addRating(9);
interstellar.getAverageRating();
interstellar.toggleCheckOutStatus();
console.log(interstellar);

const jazzMusic = new CD('Frank Sinatra', 'Christmas Songs by Sinatra', ['Jingle Bells', 'Silent Night', 'White Christmas']);
jazzMusic.addRating(7);
jazzMusic.addRating(6);
jazzMusic.addRating(10);
jazzMusic.addRating(8);
jazzMusic.addRating(9);
jazzMusic.getAverageRating();
jazzMusic.toggleCheckOutStatus();
console.log(jazzMusic);