import { Media, Book, Movie, CD } from "./resources.js";
const godfather = new Book('Mario Puzo', 'The Godfather', 532);
godfather.addRating(8);
godfather.addRating(9);
godfather.addRating(10);
godfather.addRating(10);
godfather.addRating(9);
godfather.toggleCheckOutStatus();
console.log(godfather);
console.log(godfather.getAverageRating());

const interstellar = new Movie('Christopher Nolan', 'Interstellar', 160);
interstellar.addRating(10);
interstellar.addRating(9.5);
interstellar.addRating(9);
interstellar.addRating(10);
interstellar.addRating(9);
interstellar.toggleCheckOutStatus();
console.log(interstellar);
console.log(interstellar.getAverageRating());

const jazzMusic = new CD('Frank Sinatra', 'Christmas Songs by Sinatra', ['Jingle Bells', 'Silent Night', 'White Christmas']);
jazzMusic.addRating(7);
jazzMusic.addRating(6);
jazzMusic.addRating(10);
jazzMusic.addRating(8);
jazzMusic.addRating(9);
jazzMusic.toggleCheckOutStatus();
console.log(jazzMusic);
console.log(jazzMusic.getAverageRating());